-- initial vehicle records are from https://github.com/iLeaksy/fivem-vehicle-list

CREATE TABLE IF NOT EXISTS `vehicles` (
  `name` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  `model` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  `price` int(11) NOT NULL,
  `category` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`model`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO `vehicles` (`name`, `model`, `price`, `category`) VALUES
    ("Truffade Adder", "adder", 900000, "super"),
    ("Dinka Akuma", "akuma", 7500, "motorcycles"),
    ("Albany Alpha", "alpha", 60000, "sports"),
    ("Maxwell Asbo", "asbo", 8000, "compacts"),
    ("Declasse Asea", "asea", 5500, "sedans"),
    ("Karin Asterope", "asterope", 45000, "sedans"),
    ("Pfister Astron", "astron", 20000, "suvs"),
    ("Overflod Autarch", "autarch", 1955000, "super"),
    ("LCC Avarus", "avarus", 18000, "motorcycles"),
    ("Western Bagger", "bagger", 13500, "motorcycles"),
    ("Gallivanter Baller", "baller2", 40000, "suvs"),
    ("Gallivanter Baller LE", "baller3", 60000, "suvs"),
    ("Gallivanter Baller LE LWB", "baller4", 60000, "suvs"),
    ("Gallivanter Baller ST", "baller7", 20000, "suvs"),
    ("Bravado Banshee", "banshee", 70000, "sports"),
    ("Bravado Banshee 900R", "banshee2", 255000, "super"),
    ("Pegassi Bati 801", "bati", 12000, "motorcycles"),
    ("Pegassi Bati 801RR", "bati2", 19000, "motorcycles"),
    ("Grotti Bestia GTS", "bestiagts", 55000, "sports"),
    ("Nagasaki BF400", "bf400", 6500, "motorcycles"),
    ("BF Injection", "bfinjection", 16000, "offroad"),
    ("BF Bifta", "bifta", 12000, "offroad"),
    ("Bravado Bison", "bison", 45000, "vans"),
    ("Bravado Bison", "bison2", 20000, "vans"),
    ("Karin BeeJay XL", "bjxl", 45000, "suvs"),
    ("Vapid Blade", "blade", 15000, "muscle"),
    ("Nagasaki Blazer", "blazer", 6500, "offroad"),
    ("Nagasaki Street Blazer", "blazer4", 8500, "offroad"),
    ("Dinka Blista", "blista", 8000, "compacts"),
    ("Dinka Blista Compact", "blista2", 45000, "sports"),
    ("Dinka Go Go Monkey Blista", "blista3", 45000, "sports"),
    (" BMX", "bmx", 160, "cycles"),
    ("Vapid Bobcat XL", "bobcatxl", 32000, "vans"),
    ("Canis Bodhi", "bodhi2", 45000, "offroad"),
    ("Karin Boor", "boor", 20000, "muscle"),
    ("Coil Brawler", "brawler", 45000, "offroad"),
    ("Grotti Brioso R/A", "brioso", 18000, "compacts"),
    ("Grotti Brioso 300", "brioso2", 8000, "compacts"),
    ("Classique Broadway", "broadway", 20000, "muscle"),
    ("Albany Roosevelt", "btype", 62000, "sportsclassics"),
    ("Albany Fränken Stange", "btype2", 155000, "sportsclassics"),
    ("Albany Roosevelt Valor", "btype3", 85000, "sportsclassics"),
    ("Albany Buccaneer", "buccaneer", 18000, "muscle"),
    ("Albany Buccaneer Custom", "buccaneer2", 24000, "muscle"),
    ("Bravado Buffalo", "buffalo", 12000, "sports"),
    ("Bravado Buffalo S", "buffalo2", 20000, "sports"),
    ("Bravado Sprunk Buffalo", "buffalo3", 20000, "sports"),
    ("Bravado Buffalo STX", "buffalo4", 20000, "muscle"),
    ("Vapid Bullet", "bullet", 90000, "super"),
    ("Declasse Bugstars Burrito", "burrito2", 20000, "vans"),
    ("Declasse Burrito", "burrito3", 19000, "vans"),
    ("Declasse Burrito", "burrito4", 20000, "vans"),
    ("Karin Calico GTF", "calico", 2000, "sports"),
    ("Brute Camper", "camper", 42000, "vans"),
    ("Vapid Caracara 4x4", "caracara2", 20000, "offroad"),
    ("Grotti Carbonizzare", "carbonizzare", 75000, "sports"),
    ("Nagasaki Carbon RS", "carbonrs", 18000, "motorcycles"),
    ("Lampadati Casco", "casco", 30000, "sportsclassics"),
    ("Albany Cavalcade", "cavalcade", 45000, "suvs"),
    ("Albany Cavalcade", "cavalcade2", 55000, "suvs"),
    ("Dewbauchee Champion", "champion", 20000, "super"),
    ("RUNE Cheburek", "cheburek", 20000, "sedans"),
    ("Grotti Cheetah", "cheetah", 375000, "super"),
    ("Grotti Cheetah Classic", "cheetah2", 20000, "sports"),
    ("Nagasaki Chimera", "chimera", 38000, "motorcycles"),
    ("Vapid Chino", "chino", 15000, "muscle"),
    ("Vapid Chino Custom", "chino2", 19000, "muscle"),
    ("Lampadati Cinquemila", "cinquemila", 20000, "sedans"),
    ("Western Cliffhanger", "cliffhanger", 9500, "motorcycles"),
    ("Vapid Clique", "clique", 45000, "muscle"),
    ("BF Club", "club", 8000, "compacts"),
    ("Enus Cognoscenti 55", "cog55", 45000, "sedans"),
    ("Enus Cognoscenti Cabrio", "cogcabrio", 55000, "coupes"),
    ("Enus Cognoscenti", "cognoscenti", 55000, "sedans"),
    ("Pfister Comet", "comet2", 65000, "sports"),
    ("Pfister Comet SR", "comet5", 145000, "sports"),
    ("Pfister Comet S2", "comet6", 2000, "sports"),
    ("Pfister Comet S2 Cabrio", "comet7", 20000, "sports"),
    ("Vapid Contender", "contender", 70000, "suvs"),
    ("Invetero Coquette", "coquette", 65000, "sports"),
    ("Invetero Coquette Classic", "coquette2", 40000, "sportsclassics"),
    ("Invetero Coquette BlackFin", "coquette3", 55000, "muscle"),
    ("Lampadati Corsita", "corsita", 20000, "sports"),
    (" Cruiser", "cruiser", 510, "cycles"),
    ("Coil Cyclone", "cyclone", 1890000, "super"),
    ("Ubermacht Cypher", "cypher", 2000, "sports"),
    ("Western Daemon", "daemon", 11500, "motorcycles"),
    ("Western Daemon", "daemon2", 13500, "motorcycles"),
    ("Shitzu Defiler", "defiler", 9800, "motorcycles"),
    ("Enus Deity", "deity", 20000, "sedans"),
    ("Principe Deveste Eight", "deveste", 20000, "sports"),
    ("Schyster Deviant", "deviant", 45000, "muscle"),
    ("Principe Diabolus", "diablous", 45000, "motorcycles"),
    ("Principe Diabolus Custom", "diablous2", 45000, "motorcycles"),
    ("Karin Dilettante", "dilettante", 8000, "compacts"),
    ("Bravado Duneloader", "dloader", 45000, "offroad"),
    ("Vapid Dominator", "dominator", 35000, "muscle"),
    ("Vapid Pisswasser Dominator", "dominator2", 45000, "muscle"),
    ("Vapid Dominator GTX", "dominator3", 45000, "muscle"),
    ("Vapid Dominator ASP", "dominator7", 2000, "sports"),
    ("Vapid Dominator GTT", "dominator8", 2000, "sports"),
    ("Dinka Double-T", "double", 28000, "motorcycles"),
    ("Obey 8F Drafter", "drafter", 20000, "sports"),
    ("Benefactor Dubsta", "dubsta", 45000, "suvs"),
    ("Benefactor Dubsta", "dubsta2", 60000, "suvs"),
    ("Benefactor Dubsta 6x6", "dubsta3", 120000, "offroad"),
    ("Imponte Dukes", "dukes", 28000, "muscle"),
    ("Imponte Beater Dukes", "dukes3", 45000, "muscle"),
    ("BF Dune Buggy", "dune", 8000, "offroad"),
    ("Weeny Dynasty", "dynasty", 20000, "sports"),
    ("Annis Elegy Retro Custom", "elegy", 20000, "sports"),
    ("Annis Elegy RH8", "elegy2", 38500, "sports"),
    ("Vapid Ellie", "ellie", 45000, "muscle"),
    ("Progen Emerus", "emerus", 20000, "super"),
    ("Albany Emperor", "emperor", 8500, "sedans"),
    ("Albany Emperor", "emperor2", 45000, "sedans"),
    ("Dinka Enduro", "enduro", 5500, "motorcycles"),
    ("Overflod Entity XXR", "entity2", 20000, "super"),
    ("Overflod Entity MT", "entity3", 20000, "sports"),
    ("Overflod Entity XF", "entityxf", 425000, "super"),
    ("Pegassi Esskey", "esskey", 4200, "motorcycles"),
    ("Willard Eudora", "eudora", 20000, "muscle"),
    ("Annis Euros", "euros", 2000, "sports"),
    ("Karin Everon", "everon", 45000, "offroad"),
    ("Karin Hotring Everon", "everon2", 20000, "muscle"),
    ("Dewbauchee Exemplar", "exemplar", 32000, "coupes"),
    ("Ocelot F620", "f620", 40000, "coupes"),
    ("Willard Faction", "faction", 20000, "muscle"),
    ("Willard Faction Custom", "faction2", 30000, "muscle"),
    ("Vulcar Fagaloa", "fagaloa", 20000, "sports"),
    ("Pegassi Faggio Sport", "faggio", 1900, "motorcycles"),
    ("Pegassi Faggio", "faggio2", 2800, "motorcycles"),
    ("Pegassi Faggio Mod", "faggio3", 45000, "motorcycles"),
    ("Pegassi FCR 1000", "fcr", 45000, "motorcycles"),
    ("Pegassi FCR 1000 Custom", "fcr2", 45000, "motorcycles"),
    ("Lampadati Felon", "felon", 42000, "coupes"),
    ("Lampadati Felon GT", "felon2", 55000, "coupes"),
    ("Benefactor Feltzer", "feltzer2", 55000, "sports"),
    ("Benefactor Stirling GT", "feltzer3", 65000, "sportsclassics"),
    (" Fixter", "fixter", 225, "cycles"),
    ("Vapid Flash GT", "flashgt", 20000, "sports"),
    ("Vapid FMJ", "fmj", 185000, "super"),
    ("Fathom FQ 2", "fq2", 17000, "suvs"),
    ("Canis Freecrawler", "freecrawler", 45000, "offroad"),
    ("Cheval Fugitive", "fugitive", 12000, "sedans"),
    ("Grotti Furia", "furia", 20000, "super"),
    ("Lampadati Furore GT", "furoregt", 45000, "sports"),
    ("Schyster Fusilade", "fusilade", 40000, "sports"),
    ("Karin Futo", "futo", 20000, "sports"),
    ("Karin Futo GTX", "futo2", 2000, "sports"),
    ("Western Gargoyle", "gargoyle", 16500, "motorcycles"),
    ("Bravado Gauntlet", "gauntlet", 30000, "muscle"),
    ("Bravado Redwood Gauntlet", "gauntlet2", 45000, "muscle"),
    ("Bravado Gauntlet Classic", "gauntlet3", 45000, "muscle"),
    ("Bravado Gauntlet Hellfire", "gauntlet4", 45000, "muscle"),
    ("Bravado Gauntlet Classic Custom", "gauntlet5", 45000, "muscle"),
    ("Vapid GB200", "gb200", 20000, "sports"),
    ("Declasse Gang Burrito", "gburrito", 45000, "vans"),
    ("Declasse Gang Burrito", "gburrito2", 29000, "vans"),
    ("Benefactor Glendale", "glendale", 6500, "sedans"),
    ("Benefactor Glendale Custom", "glendale2", 45000, "sedans"),
    ("Progen GP1", "gp1", 20000, "super"),
    ("Declasse Granger", "granger", 50000, "suvs"),
    ("Declasse Granger 3600LX", "granger2", 20000, "suvs"),
    ("Bravado Greenwood", "greenwood", 20000, "muscle"),
    ("Bravado Gresley", "gresley", 47500, "suvs"),
    ("Pfister Growler", "growler", 2000, "sports"),
    ("Grotti GT500", "gt500", 785000, "sportsclassics"),
    ("Vapid Guardian", "guardian", 450000, "offroad"),
    ("Emperor Habanero", "habanero", 45000, "suvs"),
    ("Shitzu Hakuchou", "hakuchou", 31000, "motorcycles"),
    ("Shitzu Hakuchou Drag", "hakuchou2", 55000, "motorcycles"),
    ("Annis Hellion", "hellion", 45000, "offroad"),
    ("Albany Hermes", "hermes", 535000, "muscle"),
    ("LCC Hexer", "hexer", 12000, "motorcycles"),
    ("Vapid Hotknife", "hotknife", 125000, "muscle"),
    ("Declasse Hotring Sabre", "hotring", 20000, "sports"),
    ("Enus Huntley S", "huntley", 40000, "suvs"),
    ("Vapid Hustler", "hustler", 625000, "muscle"),
    ("Pegassi Ignus", "ignus", 20000, "super"),
    ("Overflod Imorgon", "imorgon", 20000, "sports"),
    ("Declasse Impaler", "impaler", 45000, "muscle"),
    ("Pegassi Infernus", "infernus", 180000, "super"),
    ("Pegassi Infernus Classic", "infernus2", 20000, "sports"),
    ("Vulcar Ingot", "ingot", 45000, "sedans"),
    ("LCC Innovation", "innovation", 23500, "motorcycles"),
    ("Karin Intruder", "intruder", 7500, "sedans"),
    ("Weeny Issi", "issi2", 10000, "compacts"),
    ("Weeny Issi Classic", "issi3", 8000, "compacts"),
    ("Weeny Issi Sport", "issi7", 20000, "sports"),
    ("Weeny Issi Rally", "issi8", 20000, "offroad"),
    ("Progen Itali GTB", "italigtb", 20000, "super"),
    ("Progen Itali GTB Custom", "italigtb2", 20000, "super"),
    ("Grotti Itali GTO", "italigto", 20000, "sports"),
    ("Grotti Itali RSX", "italirsx", 20000, "sports"),
    ("Obey I-Wagen", "iwagen", 20000, "suvs"),
    ("Ocelot Jackal", "jackal", 38000, "coupes"),
    ("Dinka Jester", "jester", 65000, "sports"),
    ("Dinka Jester (Racecar)", "jester2", 135000, "sports"),
    ("Dinka Jester Classic", "jester3", 20000, "sports"),
    ("Dinka Jester RR", "jester4", 2000, "sports"),
    ("Zirconium Journey", "journey", 6500, "vans"),
    ("Zirconium Journey II", "journey2", 20000, "vans"),
    ("Enus Jubilee", "jubilee", 20000, "suvs"),
    ("Ocelot Jugular", "jugular", 20000, "sports"),
    ("Canis Kalahari", "kalahari", 45000, "offroad"),
    ("Canis Kamacho", "kamacho", 345000, "offroad"),
    ("Dinka Blista Kanjo", "kanjo", 8000, "compacts"),
    ("Hijak Khamelion", "khamelion", 38000, "sports"),
    ("Lampadati Komoda", "komoda", 20000, "sports"),
    ("Benefactor Krieger", "krieger", 20000, "super"),
    ("Karin Kuruma", "kuruma", 30000, "sports"),
    ("Dundreary Landstalker", "landstalker", 35000, "suvs"),
    ("Dundreary Landstalker XL", "landstalker2", 45000, "suvs"),
    ("Annis RE-7B", "le7b", 325000, "super"),
    ("Benefactor LM87", "lm87", 20000, "super"),
    ("Ocelot Locust", "locust", 20000, "sports"),
    ("Ocelot Lynx", "lynx", 40000, "sports"),
    ("Declasse Mamba", "mamba", 70000, "sports"),
    ("Albany Manana", "manana", 12800, "sportsclassics"),
    ("Albany Manana Custom", "manana2", 20000, "sports"),
    ("Maibatsu Manchez", "manchez", 5300, "motorcycles"),
    ("Maibatsu Manchez Scout", "manchez2", 5300, "motorcycles"),
    ("Maibatsu Manchez Scout C", "manchez3", 20000, "motorcycles"),
    ("Dewbauchee Massacro", "massacro", 65000, "sports"),
    ("Dewbauchee Massacro (Racecar)", "massacro2", 130000, "sports"),
    ("Canis Mesa", "mesa", 16000, "suvs"),
    ("Canis Mesa", "mesa3", 40000, "suvs"),
    ("Lampadati Michelli GT", "michelli", 20000, "sports"),
    ("Vapid Minivan", "minivan", 13000, "vans"),
    ("Vapid Minivan Custom", "minivan2", 20000, "vans"),
    ("Pegassi Monroe", "monroe", 55000, "sportsclassics"),
    ("Declasse Moonbeam", "moonbeam", 18000, "vans"),
    ("Declasse Moonbeam Custom", "moonbeam2", 35000, "vans"),
    ("Maibatsu Mule", "mule5", 20000, "commercial"),
    ("Vulcar Nebula Turbo", "nebula", 20000, "sports"),
    ("Principe Nemesis", "nemesis", 5800, "motorcycles"),
    ("Pfister Neon", "neon", 1500000, "sports"),
    ("Truffade Nero", "nero", 20000, "super"),
    ("Truffade Nero Custom", "nero2", 20000, "super"),
    ("Western Nightblade", "nightblade", 35000, "motorcycles"),
    ("Imponte Nightshade", "nightshade", 65000, "muscle"),
    ("Obey 9F", "ninef", 65000, "sports"),
    ("Obey 9F Cabrio", "ninef2", 80000, "sports"),
    ("Lampadati Novak", "novak", 45000, "suvs"),
    ("Obey Omnis", "omnis", 35000, "sports"),
    ("Obey Omnis e-GT", "omnisegt", 20000, "sports"),
    ("Ubermacht Oracle XS", "oracle", 45000, "coupes"),
    ("Ubermacht Oracle", "oracle2", 35000, "coupes"),
    ("Pegassi Osiris", "osiris", 160000, "super"),
    ("Nagasaki Outlaw", "outlaw", 45000, "offroad"),
    ("Toundra Panthere", "panthere", 20000, "sports"),
    ("Benefactor Panto", "panto", 10000, "compacts"),
    ("Bravado Paradise", "paradise", 19000, "vans"),
    ("Enus Paragon R", "paragon", 20000, "sports"),
    ("Ocelot Pariah", "pariah", 1420000, "sports"),
    ("Mammoth Patriot", "patriot", 55000, "suvs"),
    ("Mammoth Patriot Stretch", "patriot2", 45000, "suvs"),
    ("Mammoth Patriot Mil-Spec", "patriot3", 20000, "offroad"),
    ("Shitzu PCJ 600", "pcj", 6200, "motorcycles"),
    ("Ocelot Penetrator", "penetrator", 20000, "super"),
    ("Maibatsu Penumbra", "penumbra", 28000, "sports"),
    ("Maibatsu Penumbra FF", "penumbra2", 20000, "sports"),
    ("Vapid Peyote", "peyote", 20000, "sports"),
    ("Vapid Peyote Gasser", "peyote2", 45000, "muscle"),
    ("Vapid Peyote Custom", "peyote3", 20000, "sports"),
    ("Pfister 811", "pfister811", 85000, "super"),
    ("Imponte Phoenix", "phoenix", 12500, "muscle"),
    ("Cheval Picador", "picador", 18000, "muscle"),
    ("Lampadati Pigalle", "pigalle", 20000, "sportsclassics"),
    ("Brute Pony", "pony", 20000, "vans"),
    ("Brute Pony", "pony2", 20000, "vans"),
    ("Western Powersurge", "powersurge", 20000, "motorcycles"),
    ("Bollokan Prairie", "prairie", 12000, "compacts"),
    ("Declasse Premier", "premier", 8000, "sedans"),
    ("Karin Previon", "previon", 2000, "sports"),
    ("Albany Primo", "primo", 45000, "sedans"),
    ("Albany Primo Custom", "primo2", 14000, "sedans"),
    ("Grotti X80 Proto", "prototipo", 2500000, "super"),
    ("Annis 300R", "r300", 20000, "sports"),
    ("Vapid Radius", "radi", 29000, "suvs"),
    ("Coil Raiden", "raiden", 1375000, "sports"),
    ("Declasse Rancher XL", "rancherxl", 45000, "offroad"),
    ("Dewbauchee Rapid GT", "rapidgt", 35000, "sports"),
    ("Dewbauchee Rapid GT", "rapidgt2", 45000, "sports"),
    ("Dewbauchee Rapid GT Classic", "rapidgt3", 885000, "sportsclassics"),
    ("BF Raptor", "raptor", 20000, "sports"),
    ("Western Rat Bike", "ratbike", 45000, "motorcycles"),
    (" Rat-Loader", "ratloader", 45000, "muscle"),
    ("Bravado Rat-Truck", "ratloader2", 45000, "muscle"),
    ("Pegassi Reaper", "reaper", 150000, "super"),
    ("Karin Rusty Rebel", "rebel", 45000, "offroad"),
    ("Karin Rebel", "rebel2", 35000, "offroad"),
    ("Ubermacht Rebla GTS", "rebla", 45000, "suvs"),
    ("Western Reever", "reever", 20000, "motorcycles"),
    ("Dundreary Regina", "regina", 5000, "sedans"),
    ("Annis Remus", "remus", 2000, "sports"),
    ("Vapid Retinue", "retinue", 615000, "sportsclassics"),
    ("Vapid Retinue Mk II", "retinue2", 20000, "sports"),
    ("Ubermacht Revolter", "revolter", 1610000, "sports"),
    ("Declasse Rhapsody", "rhapsody", 8000, "compacts"),
    ("Vapid Riata", "riata", 380000, "offroad"),
    ("Obey Rocoto", "rocoto", 45000, "suvs"),
    ("Dinka RT3000", "rt3000", 2000, "sports"),
    ("Pegassi Ruffian", "ruffian", 6800, "motorcycles"),
    ("Imponte Ruiner", "ruiner", 45000, "muscle"),
    ("Imponte Ruiner", "ruiner3", 45000, "muscle"),
    ("Bravado Rumpo", "rumpo", 15000, "vans"),
    ("Bravado Rumpo", "rumpo2", 20000, "vans"),
    ("Hijak Ruston", "ruston", 20000, "sports"),
    ("Annis S80RR", "s80", 20000, "super"),
    ("Declasse Sabre Turbo", "sabregt", 20000, "muscle"),
    ("Declasse Sabre Turbo Custom", "sabregt2", 25000, "muscle"),
    ("Maibatsu Sanchez (livery)", "sanchez", 5300, "motorcycles"),
    ("Maibatsu Sanchez", "sanchez2", 5300, "motorcycles"),
    ("LCC Sanctus", "sanctus", 25000, "motorcycles"),
    ("Vapid Sandking XL", "sandking", 55000, "offroad"),
    ("Vapid Sandking SWB", "sandking2", 45000, "offroad"),
    ("Annis Savestra", "savestra", 990000, "sportsclassics"),
    ("Ubermacht SC1", "sc1", 1603000, "super"),
    ("Benefactor Schafter", "schafter2", 25000, "sedans"),
    ("Benefactor Schafter V12", "schafter3", 50000, "sports"),
    ("Benefactor Schafter LWB", "schafter4", 20000, "sports"),
    ("Benefactor Schlagen GT", "schlagen", 20000, "sports"),
    ("Benefactor Schwartzer", "schwarzer", 20000, "sports"),
    (" Scorcher", "scorcher", 280, "cycles"),
    ("Canis Seminole", "seminole", 25000, "suvs"),
    ("Canis Seminole Frontier", "seminole2", 45000, "suvs"),
    ("Ubermacht Sentinel XS", "sentinel", 32000, "coupes"),
    ("Ubermacht Sentinel", "sentinel2", 40000, "coupes"),
    ("Ubermacht Sentinel Classic", "sentinel3", 650000, "sports"),
    ("Benefactor Serrano", "serrano", 45000, "suvs"),
    ("Dewbauchee Seven-70", "seven70", 39500, "sports"),
    ("Emperor ETR1", "sheava", 220000, "super"),
    ("Nagasaki Shinobi", "shinobi", 20000, "motorcycles"),
    ("Vapid Slamvan Custom", "slamvan3", 11500, "muscle"),
    ("Western Sovereign", "sovereign", 22000, "motorcycles"),
    ("Dewbauchee Specter", "specter", 20000, "sports"),
    ("Dewbauchee Specter Custom", "specter2", 20000, "sports"),
    ("Vapid Speedo", "speedo", 20000, "vans"),
    ("Vapid Clown Van", "speedo2", 20000, "vans"),
    ("Vapid Speedo Custom", "speedo4", 20000, "vans"),
    ("Mammoth Squaddie", "squaddie", 45000, "suvs"),
    ("Enus Stafford", "stafford", 45000, "sedans"),
    ("Declasse Stallion", "stalion", 45000, "muscle"),
    ("Declasse Burger Shot Stallion", "stalion2", 45000, "muscle"),
    ("Vapid Stanier", "stanier", 45000, "sedans"),
    ("Grotti Stinger", "stinger", 80000, "sportsclassics"),
    ("Grotti Stinger GT", "stingergt", 75000, "sportsclassics"),
    ("Zirconium Stratum", "stratum", 45000, "sedans"),
    ("Benefactor Streiter", "streiter", 500000, "sports"),
    ("Dundreary Stretch", "stretch", 90000, "sedans"),
    ("Nagasaki Stryder", "stryder", 45000, "motorcycles"),
    ("Dinka Sugoi", "sugoi", 20000, "sports"),
    ("Karin Sultan", "sultan", 15000, "sports"),
    ("Karin Sultan Classic", "sultan2", 20000, "sports"),
    ("Karin Sultan RS Classic", "sultan3", 2000, "sports"),
    ("Karin Sultan RS", "sultanrs", 65000, "super"),
    ("Enus Super Diamond", "superd", 130000, "sedans"),
    ("Benefactor Surano", "surano", 50000, "sports"),
    ("BF Surfer", "surfer", 12000, "vans"),
    ("BF Surfer", "surfer2", 20000, "vans"),
    ("BF Surfer Custom", "surfer3", 20000, "vans"),
    ("Cheval Surge", "surge", 45000, "sedans"),
    ("Ocelot Swinger", "swinger", 20000, "sports"),
    ("Progen T20", "t20", 300000, "super"),
    (" Taco Van", "taco", 20000, "vans"),
    ("Declasse Tahoma Coupe", "tahoma", 20000, "muscle"),
    ("Obey Tailgater", "tailgater", 30000, "sedans"),
    ("Obey Tailgater S", "tailgater2", 2000, "sports"),
    ("Cheval Taipan", "taipan", 20000, "super"),
    ("Declasse Tampa", "tampa", 16000, "muscle"),
    ("Declasse Drift Tampa", "tampa2", 80000, "sports"),
    ("Pegassi Tempesta", "tempesta", 20000, "super"),
    ("Pegassi Tezeract", "tezeract", 20000, "super"),
    ("Truffade Thrax", "thrax", 20000, "super"),
    ("Dinka Thrust", "thrust", 24000, "motorcycles"),
    ("Lampadati Tigon", "tigon", 20000, "super"),
    ("Pegassi Torero", "torero", 20000, "sports"),
    ("Pegassi Torero XO", "torero2", 20000, "super"),
    ("Declasse Tornado", "tornado", 20000, "sports"),
    ("Declasse Tornado", "tornado2", 20000, "sports"),
    ("Declasse Tornado", "tornado3", 20000, "sports"),
    ("Declasse Tornado", "tornado4", 20000, "sports"),
    ("Declasse Tornado Custom", "tornado5", 20000, "sports"),
    ("Declasse Tornado Rat Rod", "tornado6", 20000, "sports"),
    ("Pegassi Toros", "toros", 45000, "suvs"),
    (" Whippet Race Bike", "tribike", 520, "cycles"),
    (" Endurex Race Bike", "tribike2", 520, "cycles"),
    (" Tri-Cycles Race Bike", "tribike3", 520, "cycles"),
    ("Vapid Trophy Truck", "trophytruck", 60000, "offroad"),
    ("Vapid Desert Raid", "trophytruck2", 80000, "offroad"),
    ("Lampadati Tropos Rallye", "tropos", 40000, "sports"),
    ("Declasse Tulip", "tulip", 45000, "muscle"),
    ("Declasse Tulip M-100", "tulip2", 20000, "muscle"),
    ("Grotti Turismo Classic", "turismo2", 20000, "sports"),
    ("Grotti Turismo R", "turismor", 350000, "super"),
    ("Overflod Tyrant", "tyrant", 20000, "super"),
    ("Progen Tyrus", "tyrus", 600000, "super"),
    ("Pegassi Vacca", "vacca", 120000, "super"),
    ("Shitzu Vader", "vader", 7200, "motorcycles"),
    ("Dewbauchee Vagner", "vagner", 20000, "super"),
    ("Maxwell Vagrant", "vagrant", 45000, "offroad"),
    ("Declasse Vamos", "vamos", 45000, "muscle"),
    ("Emperor Vectre", "vectre", 2000, "sports"),
    ("Bravado Verlierer", "verlierer2", 70000, "sports"),
    ("Dinka Verus", "verus", 45000, "offroad"),
    ("Declasse Vigero", "vigero", 12500, "muscle"),
    ("Dinka Vindicator", "vindicator", 45000, "motorcycles"),
    ("Albany Virgo", "virgo", 14000, "muscle"),
    ("Dundreary Virgo Classic Custom", "virgo2", 45000, "muscle"),
    ("Dundreary Virgo Classic", "virgo3", 45000, "muscle"),
    ("Ocelot Virtue", "virtue", 20000, "sports"),
    ("Lampadati Viseris", "viseris", 875000, "sportsclassics"),
    ("Grotti Visione", "visione", 2250000, "super"),
    ("Coil Voltic", "voltic", 90000, "super"),
    ("Declasse Voodoo Custom", "voodoo", 7200, "muscle"),
    ("Declasse Voodoo", "voodoo2", 45000, "muscle"),
    ("Pegassi Vortex", "vortex", 9800, "motorcycles"),
    ("Albany V-STR", "vstr", 20000, "sports"),
    ("Vulcar Warrener", "warrener", 4000, "sedans"),
    ("Vulcar Warrener HKR", "warrener2", 20000, "sports"),
    ("Albany Washington", "washington", 9000, "sedans"),
    ("BF Weevil", "weevil", 8000, "compacts"),
    ("Enus Windsor", "windsor", 95000, "coupes"),
    ("Enus Windsor Drop", "windsor2", 125000, "coupes"),
    ("Vapid Winky", "winky", 45000, "offroad"),
    ("Western Wolfsbane", "wolfsbane", 9000, "motorcycles"),
    ("Ocelot XA-21", "xa21", 20000, "super"),
    ("Benefactor XLS", "xls", 32000, "suvs"),
    ("Declasse Yosemite", "yosemite", 485000, "muscle"),
    ("Declasse Drift Yosemite", "yosemite2", 45000, "muscle"),
    ("Declasse Yosemite Rancher", "yosemite3", 45000, "muscle"),
    ("Bravado Youga", "youga", 10800, "vans"),
    ("Bravado Youga Classic", "youga2", 14500, "vans"),
    ("Bravado Youga Classic 4x4", "youga3", 20000, "vans"),
    ("Vapid Youga Custom", "youga4", 20000, "vans"),
    ("Karin 190z", "z190", 900000, "sportsclassics"),
    ("Overflod Zeno", "zeno", 20000, "super"),
    ("Pegassi Zentorno", "zentorno", 1500000, "super"),
    ("Ubermacht Zion", "zion", 36000, "coupes"),
    ("Ubermacht Zion Cabrio", "zion2", 45000, "coupes"),
    ("Ubermacht Zion Classic", "zion3", 20000, "sports"),
    ("Western Zombie Bobber", "zombiea", 9500, "motorcycles"),
    ("Western Zombie Chopper", "zombieb", 12000, "motorcycles"),
    ("Pegassi Zorrusso", "zorrusso", 20000, "super"),
    ("Annis ZR350", "zr350", 2000, "sports"),
    ("Truffade Z-Type", "ztype", 220000, "sportsclassics");
    

CREATE TABLE IF NOT EXISTS `vehicle_categories` (
  `name` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  `label` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO `vehicle_categories` (`name`, `label`) VALUES
    ("compacts", "Compacts"),
    ("coupes", "Coupes"),
    ("cycles", "Cycles"),
    ("motorcycles", "Motos"),
    ("muscle", "Muscle"),
    ("offroad", "Off Road"),
    ("sedans", "Sedans"),
    ("sports", "Sports"),
    ("sportsclassics", "Sports Classics"),
    ("super", "Super"),
    ("suvs", "SUVs"),
    ("vans", "Vans");
